compilers:
- compiler:
    environment: {}
    extra_rpaths:
    - /projects/global/toss3/compilers/intel/intel_2019/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64
    modules: [sierra-compiler/intel/19.0.3]
    flags: {}
    operating_system: rhel7
    paths:
      cc: /projects/global/toss3/compilers/intel/intel_2019/compilers_and_libraries_2019.3.199/linux/bin/intel64/icc
      cxx: /projects/global/toss3/compilers/intel/intel_2019/compilers_and_libraries_2019.3.199/linux/bin/intel64/icpc
      f77: /projects/global/toss3/compilers/intel/intel_2019/compilers_and_libraries_2019.3.199/linux/bin/intel64/ifort
      fc: /projects/global/toss3/compilers/intel/intel_2019/compilers_and_libraries_2019.3.199/linux/bin/intel64/ifort
    spec: intel@19.0.3.199
    target: x86_64
