compilers:
- compiler:
    spec: nvcc@=12.2.91
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: any
    modules: []
    extra_rpaths: []

# See example:  https://spack.readthedocs.io/en/latest/gpu_configuration.html
