packages:
  ascent:
    variants: ~fortran~openmp build_type=Release
  conduit:
    variants: ~fortran~hdf5_compat build_type=Release
  boost:
    version: [1.76.0]
    variants: cxxstd=17
  hdf5:
    version: [1.10.7]
    variants: +cxx+hl
  masa:
    variants: ~fortran~python
  netcdf-c:
    version: [4.7.4]
    variants: +parallel-netcdf maxdims=65536 maxvars=524288
  openfast:
    version: [master]
    variants: +cxx
  parallel-netcdf:
    version: [1.12.2]
    variants: ~fortran
  perl:
    require: "@5.34.1"
  tioga:
    version: [develop]
  hypre:
    require: "@develop"
    variants: ~fortran
  hypre2:
    require: "@develop"
    variants: ~fortran
  yaml-cpp:
    version: [0.6.3]
  trilinos:
    version: [13.4.0.2022.10.27, develop]
    variants: ~adios2~alloptpkgs~amesos~anasazi~aztec+boost~chaco~complex~debug~dtk~epetra~epetraext+exodus+explicit_template_instantiation~float~fortran~fortrilinos+glm+gtest+hdf5~hypre~ifpack~intrepid~intrepid2~isorropia+kokkos~mesquite+metis~minitensor~ml+mpi~mumps~nox~openmp~phalanx~piro~python~rol~rythmos~sacado+shards~shylu+stk~stratimikos~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra+uvm~x11~xsdkflags+zlib+zoltan+zoltan2 gotype=long cxxstd=17 build_type=Release
  all:
    variants: build_type=Release +mpi
    providers:
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
