compilers:
  - compiler:
      spec: clang@15.0.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-cray-amd/8.3.3
      - rocm/5.4.3
      - amd/5.4.3
      - libfabric
      - craype-x86-trento
      extra_rpaths: []
      environment:
        prepend_path:
          PKG_CONFIG_PATH: /opt/cray/xpmem/2.5.2-2.4_3.30__gd0f7936.shasta/lib64/pkgconfig/
