packages:
  cray-mpich:
    version: [8.1.17]
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.17%clang@14.0.0"
        prefix: /opt/cray/pe/mpich/8.1.17/ofi/amd/5.0
        modules:
          - cray-mpich/8.1.17
          - craype-network-ofi
  rocprim:
    version: [5.4.0]
    buildable: false
    externals:
      - spec: rocprim@5.4.0
        prefix: /opt/rocm-5.4.0/rocprim
        modules:
          - rocm/5.4.0
          - craype-accel-amd-gfx90a
  rocrand:
    version: [5.4.0]
    buildable: false
    externals:
      - spec: rocrand@5.4.0
        prefix: /opt/rocm-5.4.0/rocrand
        modules:
          - rocm/5.4.0
          - craype-accel-amd-gfx90a
  rocthrust:
    version: [5.4.0]
    buildable: false
    externals:
      - spec: rocthrust@5.4.0
        prefix: /opt/rocm-5.4.0/rocthrust
        modules:
          - rocm/5.4.0
          - craype-accel-amd-gfx90a
  rocsparse:
    version: [5.4.0]
    buildable: false
    externals:
      - spec: rocsparse@5.4.0
        prefix: /opt/rocm-5.4.0/rocsparse
        modules:
          - rocm/5.4.0
          - craype-accel-amd-gfx90a
  hip:
    version: [5.4.0]
    buildable: false
    externals:
      - spec: hip@5.4.0
        prefix: /opt/rocm-5.4.0
        modules:
          - rocm/5.4.0
          - craype-accel-amd-gfx90a
  hsa-rocr-dev:
    version: [5.4.0]
    buildable: false
    externals:
      - spec: hsa-rocr-dev@5.4.0
        prefix: /opt/rocm-5.4.0/hsa
        modules:
          - rocm/5.4.0
          - craype-accel-amd-gfx90a
  llvm-amdgpu:
    version: [5.4.0]
    buildable: false
    externals:
      - spec: llvm-amdgpu@5.4.0
        prefix: /opt/rocm-5.4.0/llvm
        modules:
          - rocm/5.4.0
          - craype-accel-amd-gfx90a
  cmake:
    version: [3.23.2]
    buildable: false
    externals:
      - spec: cmake@3.23.2
        prefix: /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i7tchi64s3qd
        modules:
          - cmake/3.23.2
  perl:
    version: [5.34.1]
    buildable: false
    externals:
      - spec: perl@5.34.1
        prefix: /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/perl-5.34.0-2f4kqqwg4xkrrapb5peh5m6fw2cargdl
        modules:
          - perl/5.34.0
  openblas:
    version: [0.3.17]
    buildable: false
    externals:
      - spec: openblas@0.3.17
        prefix: /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/openblas-0.3.17-54x7v5e4i6yxqs6j5nebrbztpy4lftj4
        modules:
          - openblas/0.3.17
  all:
    compiler:
      - clang@14.0.0
    providers:
      mpi: [cray-mpich@8.1.17]
      blas: [openblas]
      lapack: [openblas]
    variants: build_type=Release amdgpu_target=gfx90a
