packages:
  cray-mpich:
    version: [8.1.17]
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.17%clang@14.0.0"
        prefix: /opt/cray/pe/mpich/8.1.17/ofi/amd/5.0
        modules:
          - cray-mpich/8.1.17
          - craype-network-ofi
  rocprim:
    version: [5.2.0]
    buildable: false
    externals:
      - spec: rocprim@5.2.0
        prefix: /opt/rocm-5.2.0/rocprim
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocrand:
    version: [5.2.0]
    buildable: false
    externals:
      - spec: rocrand@5.2.0
        prefix: /opt/rocm-5.2.0/rocrand
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocthrust:
    version: [5.2.0]
    buildable: false
    externals:
      - spec: rocthrust@5.2.0
        prefix: /opt/rocm-5.2.0/thrust
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocsparse:
    version: [5.2.0]
    buildable: false
    externals:
      - spec: rocsparse@5.2.0
        prefix: /opt/rocm-5.2.0/rocsparse
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hip:
    version: [5.2.0]
    buildable: false
    externals:
      - spec: hip@5.2.0
        prefix: /opt/rocm-5.2.0/hip
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hsa-rocr-dev:
    version: [5.2.0]
    buildable: false
    externals:
      - spec: hsa-rocr-dev@5.2.0
        prefix: /opt/rocm-5.2.0/hsa
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  llvm-amdgpu:
    version: [5.2.0]
    buildable: false
    externals:
      - spec: llvm-amdgpu@5.2.0
        prefix: /opt/rocm-5.2.0/llvm
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  boost:
    version: [1.78.0]
    buildable: false
    externals:
      - spec: boost@1.78.0
        prefix: /sw/crusher/spack-envs/base/opt/cray-sles15-zen3/clang-14.0.0-rocm5.2.0/boost-1.78.0-jbrbfctoofn4arugu4odymojnwmpwzjm
        modules:
          - boost/1.78.0
  hdf5:
    version: [1.12.1]
    buildable: false
    externals:
      - spec: hdf5@1.12.1
        prefix: /sw/crusher/spack-envs/base/opt/cray-sles15-zen3/clang-14.0.0-rocm5.2.0/hdf5-1.12.1-4kj7jfpwnbznydhd2xqdtij33v2bnubm/
        modules:
          - hdf5/1.12.1
  parallel-netcdf:
    version: [1.12.2]
    buildable: false
    externals:
      - spec: parallel-netcdf@1.12.2
        prefix: /sw/crusher/spack-envs/base/opt/cray-sles15-zen3/clang-14.0.0-rocm5.2.0/parallel-netcdf-1.12.2-drkexm72gy4goprfr42vylekntbvloea
        modules:
          - parallel-netcdf/1.12.2
  cmake:
    version: [3.23.2]
    buildable: false
    externals:
      - spec: cmake@3.23.2
        prefix: /sw/crusher/spack-envs/base/opt/cray-sles15-zen3/clang-14.0.0-rocm5.2.0/cmake-3.23.2-veonilm53zmocipgahbmqvnpmboyqyvt
        modules:
          - cmake/3.23.2
  zlib:
    version: [1.2.12]
    buildable: false
    externals:
      - spec: zlib@1.2.12
        prefix: /sw/crusher/spack-envs/base/opt/cray-sles15-zen3/clang-14.0.0-rocm5.2.0/zlib-1.2.12-3puegeev5gkgpnwp7zc4tvxouzvjjfrz
        modules:
          - zlib/1.2.12
  perl:
    version: [5.34.0]
    buildable: false
    externals:
      - spec: perl@5.34.0
        prefix: /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/perl-5.34.0-2f4kqqwg4xkrrapb5peh5m6fw2cargdl
        modules:
          - perl/5.34.0
  openblas:
    version: [0.3.17]
    buildable: false
    externals:
      - spec: openblas@0.3.17
        prefix: /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/openblas-0.3.17-54x7v5e4i6yxqs6j5nebrbztpy4lftj4
        modules:
          - openblas/0.3.17
  umpire:
    version: [6.0.0]
    buildable: false
    externals:
      - spec: umpire@6.0.0
        prefix: /sw/crusher/spack-envs/base/opt/cray-sles15-zen3/cce-14.0.0/umpire-6.0.0-k6euxcfvl642cbaixqy4g2yircaobnot
        modules:
          - umpire/6.0.0
  all:
    compiler:
      - clang@14.0.0
    providers:
      mpi: [cray-mpich@8.1.17]
      blas: [openblas]
      lapack: [openblas]
    variants: amdgpu_targets=gfx90a
